### ISSUE TITLE
What license is this software under?

### ISSUE THREAD

**Issue by jbwyatt4** [reportmill/SnapKit#1]
Great project. I would like to use this.

I noticed that there is no LICENSE file or one listed in the README.

If you are interested in suggestions, I would recommend dual licensing under Apache 2.0 and Eclipse Public License (any version). This is so projects in both the Apache Java and the Eclipse community can easily add the code into their own systems.

**Comment by reportmill** [comment]
Thanks John! I haven’t figured out licensing, yet, because nobody has really asked (and I’m not knowledgable about it). I would like it to be free for anyone who needs it to be free, though I would still like to hold onto the hope of generating something to fund continued development - if ever a commercial entity found value in it. I’m not sure what that license would look like.

In the meantime, I would be happy to issue an unlimited use license for your needs, if you have an interest (as an email statement). I think you would have a reasonable time working with it - but I’m ashamed at the lack of any documentation (other than a dozen or so projects I’ve posted at my GitHub).

What kind of project are you working on?

Jeff Martin
214.513.1636

**Comment by Immortalin** [comment]
The Apache License would be a great fit for this.

**Comment by Immortalin** [comment]
@reportmill has there been any updates on this? Is it still maintained? The library looks amazing but the lack of licensing is impeding adoption. Nobody can really try it out or use it since there's no clear license.

**Comment by reportmill** [comment]
Thanks for prodding me on this. As a first step, I have added a 'License.txt' explaining my intentions and granting licensed free use for the simplest cases.

I apologize for this uniformed approach - I don't know why I find this stuff so scary and confusing. If you have a link to a license that you think fits my need, please send it along (also if you have advice on how I attach it to the repo). I googled the apache license, but, to me, it did not clearly state that I had the right to refuse free use to large commercial entities (though I probably just didn't read it right).

**Comment by old-o** [comment]
Thanks for adding a License txt to this project.
GPL3 is kind of rare for libraries, as it forces all users to also GPL their (published) derivatives. 
In particular, the vast majority of Java libs out there uses Apache license and cannot use your libs, due to license incompatibility.

**Comment by reportmill** [comment]
My goal for licensing is that anyone who needs it to be free can use SnapKit free. Any for-profit corporation deriving significant value or revenue from SnapKit are encouraged to contribute funding for continued development and health of the project and community.

If anyone has a good (or better) example of this principle working in practice, please let me know!

**Comment by old-o** [comment]
I would say that at this point SnapKit lacks visibility and community traction.

GPL-licensed Java libraries cannot be used by Open Source projects who use the 'permissive', widely used Apache, BSD, MIT or Eclipse licenses. That's why there are very few Open Source Java libraries that use the GPL.

Even OpenJDK, who uses GPL, actually uses GPL with the 'classpath exception'.
See https://www.azul.com/blog/why-the-classpath-exception-is-so-important/

If you want SnapKit to remain a little-known framework that hardly anybody uses, the GPL might be good for you.

But I doubt that some corporate investors will stumble upon your project by sheer luck.
Usually, popularity in the Open Source world happens first, then commercial demand eventually follows.

**Comment by reportmill** [comment]
The license.txt doc makes it clear that I will gladly issues almost any license or waiver. I don't think the licensing is the problem at this point. :-)
