### ISSUE TITLE
Release on Maven Central

### ISSUE THREAD

**Issue by Immortalin** [reportmill/SnapKit#4]
It would make installing easier.

**Comment by old-o** [comment]
Yep, not being able to add this as a dependency is a real bummer.

**Comment by reportmill** [comment]
This is fixed - here's a new snippet from the readme:

https://github.com/reportmill/SnapKit/?tab=readme-ov-file#including-snapkit-with-gradle-and-maven

**Comment by old-o** [comment]
Actually, this ticket is about 'Release on Maven Central', i.e. the reliable and trusted distribution network (repository) that Maven uses by default.

Providing a 3rd party (in this case your) Maven repo, is a step in the right direction, but not a common practice anymore.

Many teams and shops do not add 3rd party repos to their pom.xml because it makes their builds less reliable.

Who knows if/when you might change that URL, take it down or delete artifacts from it.

Maven Central's big and widely trusted value lies exactly in their policy of 100% uptime, never deleting artifacts and builtin nature in all the Maven standard tools.

**Comment by konsoletyper** [comment]
From my experience, releasing to Maven Central always takes additional work: you should go to their UI, perform release manually, then wait some time when your artifacts are actually available (and there's even no notification). Also, I usually need to update site and documentation. So I chose hybrid approach instead: release 3-4 times a year artifacts that I consider "stable" enough, and release often (using build automation only) to my own repository recent artifacts, so that users could try new features. This allows me on on hand, to reduce the pain of releasing to Maven Central, and on another, still make my project available to a wider audience.

**Comment by reportmill** [comment]
I agree with @konsoletyper - I have tried to publish to maven central a handful of times with this and other projects and found the process troublesome. I just don't have the resources to spend on it until there is a larger community and/or external funding. I have used Github packages before - I might try that again (although last I checked, they required credentials to even reference a package, which was disappointing).

**Comment by old-o** [comment]
I agree that publishing to Maven Central is cumbersome.

I actually have a project that I used to publish:
https://central.sonatype.com/artifact/org.guppy4j/libraries

I used a fully automated build and publish setup using my own Jenkins
server running at home. 

Basically you go through the motions of getting an OSS account with
Sonatype, create the GPG keys, put all the required stuff into your
parent pom, put in place a Jenkins button or bash alias for the 'mvn'
commandline.

But then that box had to be retired and now I cannot find my GPG
private key anymore.

Anyhow, the pom.xml on the linked page above is still a very good
template for publishing to Maven Central.
